# Generated by Django 6.0.4 on 2026-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время начала выполнения')),
                ('action', models.TextField(verbose_name='Действие')),
                ('pleasant_habit', models.TextField(verbose_name='Приятная привычка')),
                ('related_habit', models.TextField(verbose_name='Связанная привычка')),
                ('periodicity', models.CharField(default='every day', max_length=50, verbose_name='Периодичность')),
                ('award', models.TextField(verbose_name='Вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
