# Generated by Django 6.0.4 on 2026-05-03 10:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=True, verbose_name='Признак приятной привычки'),
        ),
    ]
